name: CI with PostgreSQL Integration Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest    

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
        ports:
          - 5432:5432

    env:
      POSTGRES_HOST: localhost 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: testdb 
      POSTGRES_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize database schema
      run: |
           # Step 4: (CRITICAL) Load the database schema into the running PostgreSQL service container.
    - name: Initialize database schema
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        echo "Waiting for PostgreSQL to be ready..."
        for i in {1..30}; do
          if pg_isready -h localhost -U postgres -p 5432; then
            break
          fi
          sleep 2
        done
        if ! pg_isready -h localhost -U postgres -p 5432; then
          echo "PostgreSQL is not ready after waiting for 60 seconds. Exiting."
          exit 1
        fi
        echo "PostgreSQL is ready! Loading schema..."
        psql -h localhost -U postgres -d testdb -f init.sql
      # Set the password for psql/pg_isready to avoid an interactive prompt
      env:
        PGPASSWORD: postgres


    - name: Run integration tests with pytest
      run: |
        python -m pytest tests/test_db_integration.py -v